version: 2.1
orbs:
    node: circleci/node@5.0.1
    aws-cli: circleci/aws-cli@2.1.0
    eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
    build:
        docker:
            - image: "cimg/base:stable"
        steps:
            - checkout
            - node/install
            - run:
                name: Front-End Install
                command: |
                    npm run frontend:install
            - run:
                name: Back-End Install
                command: |
                    npm run backend:install
            - run:
                name: Front-End Build
                command: |
                    npm run frontend:build
            - run:
                name: Back-End Build
                command: |
                    npm run backend:build
            - persist_to_workspace:
                root: ~/project
                paths:
                    - .
    deploy:
        docker:
            - image: "cimg/base:stable"
        steps:
            - checkout
            - node/install
            - aws-cli/setup
            - eb/setup
            - run:
                name: AWS Configure
                command: |
                    aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID" --profile default
                    aws configure set aws_secret_access_key "$AWS_ACCESS_KEY_SECRET" --profile default
                    aws configure set region "$AWS_REGION" --profile default
            - run:
                name: Back-End Elastic Beanstack initialization
                command: |
                    npm run backend:init
            - run:
                name: Back-End Deploy
                command: |
                    npm run backend:deploy
            - attach_workspace:
                at: ~/project
            - run:
                name: Front-End Deploy
                command: |
                    npm run frontend:deploy

workflows:
  build-approval-deploy:
    jobs:
      - build
      - deploy:
            requires:
                - build