version: 2.1
orbs:
    node: circleci/node@5.0.1
    # aws-cli: circleci/aws-cli@2.1.0
jobs:
    build:
        docker:
            - image: "cimg/base:stable"
        steps:
            - checkout
            - node/install
            - run:
                name: Front-End Install
                command: |
                    npm run frontend:install
